module Textus
  # Single source of truth for every path textus owns under a store root.
  # All disposable runtime state nests under <root>/.run/ so the
  # tracked/disposable boundary is a directory boundary. ADR 0038.
  module Layout
    RUN = ".run"
    DATA = "data"

    def self.data(root)
      File.join(root, DATA)
    end

    def self.data_lane(root, lane_name)
      File.join(data(root), lane_name)
    end

    def self.run(root)
      File.join(root, RUN)
    end

    def self.state(root)
      File.join(run(root), "state")
    end

    def self.cursor(root, role)
      File.join(state(root), "cursor.#{role}")
    end

    def self.locks(root)
      File.join(run(root), "locks")
    end

    def self.build_lock(root)
      File.join(run(root), "build.lock")
    end

    def self.watcher_lock(root)
      File.join(run(root), "watcher.lock")
    end

    def self.queue(root)
      File.join(run(root), "queue")
    end

    def self.queue_state(root, state)
      File.join(queue(root), state.to_s)
    end

    def self.audit_dir(root)
      File.join(run(root), "audit")
    end

    # Sentinels are machine-generated (the published target's sha), not authored
    # source, so they live on the runtime side under `.run/` — git-ignored,
    # regenerated by the next build via content-identical adoption (ADR 0070,
    # superseding ADR 0038's `:config` classification).
    def self.sentinels(root)
      File.join(run(root), "sentinels")
    end

    def self.audit_log(root)
      File.join(audit_dir(root), "audit.log")
    end

    # The store's `.gitignore` body. Always ignores the runtime subtree
    # (`.run/`, ADR 0038); when given untracked entry paths (entries marked
    # `tracked: false`), it also lists those so they stay protocol-readable but
    # uncommitted (ADR 0043, refining 0038). Generated, never hand-kept — no
    # drift between the manifest and the ignore file.
    def self.gitignore_body(untracked_paths: [])
      lines = ["# textus runtime artifacts — safe to delete, never commit",
               "#{RUN}/"]
      unless untracked_paths.empty?
        lines << "# tracked:false entries — protocol-readable, not committed (sensitive)"
        lines.concat(untracked_paths)
      end
      "#{lines.join("\n")}\n"
    end

    # Back-compat constant: the no-untracked-entries body (just the run subtree).
    GITIGNORE = gitignore_body
  end
end
