#!/usr/bin/env bash
# PreToolUse hook — block direct writes to textus-managed published artifacts.
#
# These files are generated by `textus drain` from canonical store entries.
# Writing to them directly breaks the protocol and will be overwritten on the
# next drain run. Use the textus protocol instead:
#
#   bundle exec exe/textus put KEY --stdin --as=automation
#   bundle exec exe/textus drain --as=automation
#
# To find the key for a published path:
#   bundle exec exe/textus where FRAGMENT

set -euo pipefail

block_message() {
  local rel_path="$1"
  cat >&2 <<EOF

  ✗  Direct write blocked — textus-managed artifact

     File:  $rel_path

  This file is published by \`textus drain\` from canonical store entries.
  Editing it directly will be overwritten on the next drain run.

  ── Use the textus protocol ───────────────────────────────────────────────

  1. Find the store key for this path:
       bundle exec exe/textus where $(basename "$rel_path")

  2. Write to the store (with the correct role/key):
       echo '...' | bundle exec exe/textus put KEY --stdin --as=automation

  3. Publish to the repo:
       bundle exec exe/textus drain --as=automation

  ─────────────────────────────────────────────────────────────────────────

EOF
}

# ── main ───────────────────────────────────────────────────────────────────

# Parse file_path from the PreToolUse JSON payload on stdin.
INPUT=$(cat)
FILE_PATH=$(python3 -c "
import sys, json
d = json.load(sys.stdin)
print(d.get('tool_input', {}).get('file_path', ''))
" <<< "$INPUT" 2>/dev/null) || true

[ -z "$FILE_PATH" ] && exit 0

# Resolve repo root from cwd (hooks run from the project root).
REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null || pwd)

# Strip repo root prefix to get a repo-relative path.
REL_PATH="${FILE_PATH#"$REPO_ROOT"/}"

# If path didn't change, the file is outside the repo — skip.
[ "$REL_PATH" = "$FILE_PATH" ] && exit 0

# Published artifact prefixes — anything under these directories.
# Update when new artifact trees are added to the manifest.
PROTECTED_PREFIXES=(
  "docs/"
  ".claude-plugin/"
)

# Published artifact exact paths — root-level files managed by drain.
PROTECTED_EXACT=(
  "AGENTS.md"
  "CHANGELOG.md"
  "CLAUDE.md"
  "CODE_OF_CONDUCT.md"
  "CONTRIBUTING.md"
  "README.md"
  "SECURITY.md"
  ".mcp.json"
  "opencode.json"
)

for prefix in "${PROTECTED_PREFIXES[@]}"; do
  if [[ "$REL_PATH" == "$prefix"* ]]; then
    block_message "$REL_PATH"
    exit 2
  fi
done

for exact in "${PROTECTED_EXACT[@]}"; do
  if [[ "$REL_PATH" == "$exact" ]]; then
    block_message "$REL_PATH"
    exit 2
  fi
done

exit 0
