require "fileutils"

module Textus
  module Pipeline
    module Acquire
      # Builds an entry's DATA artifact (ADR 0094) by running the projection
      # pipeline; rendering is a publish concern. External entries are NOT built
      # here — they are generated by an out-of-band runner; Derived#publish_via
      # filters them out before reaching this point.
      #
      # Merges the former Write::DataBuilder wrapper and Builder::Pipeline module
      # into one class (ADR 0100 produce/ topology refactor).
      class Projection
        # Injects provenance metadata as the first key in the serialized output.
        # Carries only deterministic provenance (`from`/`reduce`) — the volatile
        # `generated_at` is deliberately NOT stamped, so the built artifact is
        # content-addressed and a rebuild is a byte-for-byte no-op (ADR 0070).
        # Build time lives out of the tracked artifact.
        module InjectMeta
          def self.call(content_hash, mentry)
            meta = {}
            if mentry.derived?
              src = mentry.source
              if src.projection?
                from = Array(src.select).compact
                meta["from"] = from unless from.empty?
                meta["reduce"] = src.transform if src.transform
              end
            end

            out = { "_meta" => meta }
            content_hash.each { |k, v| out[k] = v unless k == "_meta" }
            out
          end
        end

        Deps = Data.define(:manifest, :reader, :lister, :steps, :transform_context)

        def self.renderers
          @renderers ||= {
            "text" => Textus::Pipeline::Acquire::Serializer::Text,
            "json" => Textus::Pipeline::Acquire::Serializer::Json,
            "yaml" => Textus::Pipeline::Acquire::Serializer::Yaml,
          }
        end

        def initialize(container:, call:)
          @container  = container
          @call       = call
          @manifest   = container.manifest
          @file_store = container.file_store
          @steps      = container.steps
          @root       = container.root
        end

        # Runs the projection pipeline for `mentry` and returns the on-disk
        # target_path string.
        def run(mentry)
          reader = lambda do |key|
            Textus::Action::Get.new(key: key).call(container: @container, call: @call)
          end
          # Projections must be able to read source data from any nested entry,
          # including keyless (publish_tree) ones like knowledge.decisions.
          # The `include_keyless: true` option makes the resolver walk those dirs
          # without exposing them on the public `list` / CLI surface (ADR 0047).
          resolver = @manifest.resolver
          lister = lambda do |prefix:|
            resolver.enumerate(prefix: prefix, include_keyless: true)
                    .map { |row| { "key" => row[:key], "lane" => row[:manifest_entry].lane, "path" => row[:path] } }
          end
          self.class.pipeline_run(
            mentry: mentry,
            deps: Deps.new(
              manifest: @manifest,
              reader: reader,
              lister: lister,
              steps: @steps,
              transform_context: @container,
            ),
          )
        end

        def self.pipeline_run(mentry:, deps:)
          # 1. Load sources + project + reduce. Only projection-derived entries are
          # buildable in-process; External entries are generated out-of-band and are
          # filtered out upstream (Derived#publish_via), so reaching here with a
          # non-projection source is a wiring bug — fail loudly rather than emit an
          # empty payload (and never re-stamp the volatile generated_at, ADR 0070).
          unless mentry.projection?
            raise UsageError.new(
              "builder: '#{mentry.key}' is not a projection-derived entry; only projections are buildable",
            )
          end

          data =
            Textus::Projection.new(
              reader: deps.reader,
              spec: mentry.source.projection_spec,
              lister: deps.lister,
              steps: deps.steps,
              transform_context: deps.transform_context,
            ).run

          # 2. Serialize as DATA. Rendering through a template is a publish concern
          # (ADR 0094) — the build never consults a template.
          klass = renderers[mentry.format] or
            raise UsageError.new("builder: unsupported data format #{mentry.format.inspect} for '#{mentry.key}'")
          bytes = klass.new.call(mentry: mentry, data: data)

          # 3. Write (idempotent: skip if only generated_at would differ)
          target_path = Key::Path.resolve(deps.manifest.data, mentry)
          FileUtils.mkdir_p(File.dirname(target_path))
          write_if_changed(target_path, bytes, mentry.format)

          target_path
        end

        # Built artifacts are content-addressed (no volatile timestamp, ADR 0070),
        # so identity is plain byte-equality: skip the write when nothing changed.
        # `format` is retained for signature stability across renderers.
        def self.write_if_changed(target_path, bytes, _format)
          return if File.exist?(target_path) && File.binread(target_path) == bytes

          File.binwrite(target_path, bytes)
        end
      end
    end
  end
end
