<!-- Generated by textus. Do not edit by hand — edit .textus/templates/docs/reference/contributor-conventions.erb and run `textus drain`. -->

# Contributor Conventions

This reference captures engineering conventions for evolving textus safely.

## Dependency Adoption Gate

All new runtime dependencies MUST pass the Dependency Adoption Gate before adoption.

- New dependencies MUST sit behind a `Textus::DependencyAdapters::*` module.
- Adapter APIs MUST be minimal and owned by textus (no full-gem pass-through wrappers).
- Call sites MUST depend on adapter interfaces at seams (ports, surfaces, runners), not on gem classes deep in domain modules.
- Tests MUST target the adapter interface and seam behavior, not vendor internals.
- Every dependency SHOULD document an exit path (how to replace or remove it).

Runtime-critical dependencies (`mcp`, `sqlite3`, `concurrent-ruby`) are adapter-first.

For the full checklist and rationale, see `docs/reference/dependency-adoption-gate.md`.
