require "zeitwerk"
require_relative "textus/version"

loader = Zeitwerk::Loader.for_gem
loader.inflector.inflect(
  "cli" => "CLI",
  "json" => "Json",
  "yaml" => "Yaml",
)

# Existing require_relative block stays until Task 13 verifies Zeitwerk
# resolves every constant on its own.
require_relative "textus/errors"
require_relative "textus/hooks/dispatcher"
require_relative "textus/hooks/loader"
require_relative "textus/hooks/registry"
require_relative "textus/role"
require_relative "textus/store/audit_log"
require_relative "textus/etag"
require_relative "textus/entry/base"
require_relative "textus/entry/markdown"
require_relative "textus/entry/json"
require_relative "textus/entry/yaml"
require_relative "textus/entry/text"
require_relative "textus/entry"
require_relative "textus/schema"
require_relative "textus/key/grammar"
require_relative "textus/key/distance"
require_relative "textus/key/path"
require_relative "textus/manifest/entry"
require_relative "textus/manifest"
require_relative "textus/envelope"
require_relative "textus/dependencies"
require_relative "textus/store/reader"
require_relative "textus/store/writer"
require_relative "textus/store/validator"
require_relative "textus/store/staleness"
require_relative "textus/store/mover"
require_relative "textus/store"
require_relative "textus/store/view"
require_relative "textus/refresh"
require_relative "textus/mustache"
require_relative "textus/projection"
require_relative "textus/hooks/builtin"
require_relative "textus/publisher"
require_relative "textus/builder/renderer" # base first
require_relative "textus/builder/renderer/markdown"
require_relative "textus/builder/renderer/text"
require_relative "textus/builder/renderer/json"
require_relative "textus/builder/renderer/yaml"
require_relative "textus/builder/pipeline"
require_relative "textus/builder"
require_relative "textus/proposal"
require_relative "textus/init"
require_relative "textus/schema/tools"
require_relative "textus/migrate_keys"
require_relative "textus/doctor/check"
require_relative "textus/doctor/check/manifest_files"
require_relative "textus/doctor/check/schemas"
require_relative "textus/doctor/check/templates"
require_relative "textus/doctor/check/extensions"
require_relative "textus/doctor/check/illegal_keys"
require_relative "textus/doctor/check/sentinels"
require_relative "textus/doctor/check/audit_log"
require_relative "textus/doctor/check/unowned_schema_fields"
require_relative "textus/doctor/check/schema_violations"
require_relative "textus/doctor"
require_relative "textus/intro"
# CLI verb command objects — base class first, then verbs alphabetically.
require_relative "textus/cli/verb"
require_relative "textus/cli/group"
require_relative "textus/cli/verb/accept"
require_relative "textus/cli/verb/build"
require_relative "textus/cli/verb/delete"
require_relative "textus/cli/verb/deps"
require_relative "textus/cli/verb/doctor"
require_relative "textus/cli/verb/get"
require_relative "textus/cli/verb/hook_run"
require_relative "textus/cli/verb/hooks"
require_relative "textus/cli/verb/init"
require_relative "textus/cli/verb/intro"
require_relative "textus/cli/verb/list"
require_relative "textus/cli/verb/migrate_keys"
require_relative "textus/cli/verb/mv"
require_relative "textus/cli/verb/published"
require_relative "textus/cli/verb/put"
require_relative "textus/cli/verb/rdeps"
require_relative "textus/cli/verb/refresh"
require_relative "textus/cli/verb/schema"
require_relative "textus/cli/verb/schema_diff"
require_relative "textus/cli/verb/schema_init"
require_relative "textus/cli/verb/schema_migrate"
require_relative "textus/cli/verb/stale"
require_relative "textus/cli/verb/uid"
require_relative "textus/cli/verb/where"
require_relative "textus/cli/group/key"
require_relative "textus/cli/group/schema"
require_relative "textus/cli/group/hook"
require_relative "textus/cli"

loader.setup
