name: plugin
required: [name, version, description, author]
fields:
  name:        { type: string, maintained_by: human }
  version:     { type: string, maintained_by: human }
  description: { type: string, maintained_by: human }
  author:      { type: object, maintained_by: human }
  repository:  { type: string, maintained_by: human }
evolution:
  added_in: 2026-05-19
