require "fileutils"

module Textus
  module Write
    # Builds an entry's DATA artifact (ADR 0094) by running the projection
    # pipeline; rendering is a publish concern. External entries are NOT built
    # here — they are generated by an out-of-band runner; Derived#publish_via
    # filters them out before reaching this point.
    class DataBuilder
      def initialize(container:, call:)
        @container  = container
        @call       = call
        @manifest   = container.manifest
        @file_store = container.file_store
        @rpc        = container.rpc
        @root       = container.root
      end

      # Runs the builder pipeline for `mentry` and returns the on-disk
      # target_path string.
      def run(mentry)
        reader = Textus::Read::Get.new(container: @container, call: @call)
        lister = Textus::Read::List.new(container: @container)
        Builder::Pipeline.run(
          mentry: mentry,
          deps: Builder::Pipeline::Deps.new(
            manifest: @manifest,
            reader: reader.method(:call),
            lister: lister.method(:call),
            rpc: @rpc,
            transform_context: @container,
          ),
        )
      end
    end
  end
end
